# Generated by Django 4.2.9 on 2026-02-01 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('campaign_type', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente'), ('manual', 'Manual'), ('preview', 'Preview')], max_length=20, verbose_name='Tipo de Campaña')),
                ('dialer_type', models.CharField(blank=True, choices=[('predictive', 'Marcador Predictivo'), ('progressive', 'Marcador Progresivo'), ('preview', 'Marcador Preview'), ('manual', 'Marcación Manual')], max_length=20, null=True, verbose_name='Tipo de Marcador')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('finished', 'Finalizada'), ('draft', 'Borrador')], default='draft', max_length=20, verbose_name='Estado')),
                ('max_calls_per_agent', models.IntegerField(default=1, verbose_name='Máx. llamadas por agente')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Máx. reintentos')),
                ('retry_delay', models.IntegerField(default=300, help_text='Segundos entre reintentos', verbose_name='Retardo entre reintentos')),
                ('call_timeout', models.IntegerField(default=30, verbose_name='Timeout de llamada (seg)')),
                ('start_date', models.DateTimeField(verbose_name='Fecha inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin')),
                ('schedule_start_time', models.TimeField(blank=True, null=True, verbose_name='Hora inicio diario')),
                ('schedule_end_time', models.TimeField(blank=True, null=True, verbose_name='Hora fin diario')),
                ('script_template', models.TextField(blank=True, verbose_name='Guión de llamada')),
                ('form_fields', models.JSONField(blank=True, default=dict, verbose_name='Campos del formulario')),
                ('total_contacts', models.IntegerField(default=0, verbose_name='Total contactos')),
                ('contacted', models.IntegerField(default=0, verbose_name='Contactados')),
                ('successful', models.IntegerField(default=0, verbose_name='Exitosos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='queues.queue')),
                ('contact_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='contacts.contactlist')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_success', models.BooleanField(default=False, verbose_name='¿Es exitosa?')),
                ('requires_callback', models.BooleanField(default=False, verbose_name='¿Requiere rellamada?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Calificación de Campaña',
                'verbose_name_plural': 'Calificaciones de Campaña',
                'db_table': 'campaign_dispositions',
                'ordering': ['campaign', 'order', 'name'],
                'unique_together': {('campaign', 'code')},
            },
        ),
    ]
