# Generated by Django 4.2.9 on 2026-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agentbreakreason_created_at'),
        ('campaigns', '0002_campaign_dnc_preview_skills_tz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='dnc_enabled',
            field=models.BooleanField(default=True, help_text='Verificar lista negra antes de marcar.', verbose_name='Activar DNC'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='preview_timeout',
            field=models.IntegerField(default=30, help_text='Segundos para revisar datos del contacto antes de marcar.', verbose_name='Timeout Preview (seg)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='campaigns_requiring', to='agents.agentgroup', verbose_name='Skills requeridos'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='timezone',
            field=models.CharField(default='America/Bogota', max_length=50, verbose_name='Zona horaria campaña'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='vip_priority_boost',
            field=models.IntegerField(default=10, verbose_name='Boost prioridad VIP'),
        ),
    ]
