# Generated by Django 4.2.9 on 2026-02-01 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True, verbose_name='ID Llamada')),
                ('channel', models.CharField(blank=True, max_length=200, verbose_name='Canal')),
                ('unique_id', models.CharField(blank=True, max_length=100, verbose_name='Unique ID')),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], max_length=10, verbose_name='Dirección')),
                ('status', models.CharField(choices=[('initiated', 'Iniciada'), ('ringing', 'Timbrando'), ('answered', 'Contestada'), ('completed', 'Completada'), ('busy', 'Ocupado'), ('no_answer', 'No Contestada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='initiated', max_length=20, verbose_name='Estado')),
                ('caller_id', models.CharField(max_length=50, verbose_name='Llamante')),
                ('called_number', models.CharField(max_length=50, verbose_name='Número llamado')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora inicio')),
                ('answer_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora respuesta')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('wait_time', models.IntegerField(default=0, verbose_name='Tiempo espera')),
                ('talk_time', models.IntegerField(default=0, verbose_name='Tiempo conversación')),
                ('hold_time', models.IntegerField(default=0, verbose_name='Tiempo retención')),
                ('recording_file', models.CharField(blank=True, max_length=500, verbose_name='Archivo grabación')),
                ('is_recorded', models.BooleanField(default=False, verbose_name='Grabada')),
                ('transferred', models.BooleanField(default=False, verbose_name='Transferida')),
                ('transfer_to', models.CharField(blank=True, max_length=100, verbose_name='Transferida a')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='agents.agent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='campaigns.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='contacts.contact')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='queues.queue')),
                ('disposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaigndisposition')),
            ],
            options={
                'verbose_name': 'Llamada',
                'verbose_name_plural': 'Llamadas',
                'db_table': 'calls',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SIPTrunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('host', models.CharField(max_length=200, verbose_name='Host/IP o FQDN')),
                ('port', models.IntegerField(default=5060, verbose_name='Puerto')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Contraseña')),
                ('codec', models.CharField(default='ulaw,alaw', max_length=100, verbose_name='Códecs')),
                ('dtmf_mode', models.CharField(default='rfc2833', max_length=20, verbose_name='Modo DTMF')),
                ('max_channels', models.IntegerField(default=10, verbose_name='Canales Máximos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Registrado')),
                ('calls_total', models.IntegerField(default=0, verbose_name='Total llamadas')),
                ('calls_active', models.IntegerField(default=0, verbose_name='Llamadas activas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Troncal SIP',
                'verbose_name_plural': 'Troncales SIP',
                'db_table': 'sip_trunks',
            },
        ),
        migrations.CreateModel(
            name='IVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('extension', models.CharField(max_length=20, unique=True, verbose_name='Extensión')),
                ('welcome_message', models.CharField(blank=True, max_length=500, verbose_name='Mensaje bienvenida')),
                ('invalid_message', models.CharField(blank=True, max_length=500, verbose_name='Mensaje opción inválida')),
                ('timeout_message', models.CharField(blank=True, max_length=500, verbose_name='Mensaje timeout')),
                ('timeout', models.IntegerField(default=5, verbose_name='Timeout (seg)')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='Intentos máximos')),
                ('menu_options', models.JSONField(default=dict, verbose_name='Opciones menú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IVR',
                'verbose_name_plural': 'IVRs',
                'db_table': 'ivr_menus',
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['start_time'], name='calls_start_t_e5e7db_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['agent', 'start_time'], name='calls_agent_i_7b9f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['campaign', 'start_time'], name='calls_campaig_a8c3e2_idx'),
        ),
    ]
