# Generated by Django 4.2.9 on 2026-02-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=20, unique=True, verbose_name='Extensión')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('extension_type', models.CharField(choices=[('SIP', 'SIP'), ('IAX2', 'IAX2'), ('PJSIP', 'PJSIP')], default='SIP', max_length=10, verbose_name='Tipo')),
                ('secret', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('context', models.CharField(choices=[('from-internal', 'from-internal'), ('from-external', 'from-external'), ('custom', 'custom')], default='from-internal', max_length=50, verbose_name='Contexto')),
                ('callerid', models.CharField(blank=True, max_length=100, verbose_name='Caller ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('voicemail_enabled', models.BooleanField(default=False, verbose_name='Buzón habilitado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extensión',
                'verbose_name_plural': 'Extensiones',
                'db_table': 'extensions',
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='InboundRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=50, unique=True, verbose_name='DID/Número')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('destination_type', models.CharField(choices=[('ivr', 'IVR'), ('queue', 'Cola'), ('extension', 'Extensión'), ('voicemail', 'Buzón de Voz'), ('announcement', 'Anuncio')], max_length=20, verbose_name='Tipo destino')),
                ('destination', models.CharField(max_length=100, verbose_name='Destino')),
                ('priority', models.IntegerField(default=1, verbose_name='Prioridad')),
                ('time_condition', models.CharField(blank=True, max_length=100, verbose_name='Condición horario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruta Entrante',
                'verbose_name_plural': 'Rutas Entrantes',
                'db_table': 'inbound_routes',
                'ordering': ['priority', 'did'],
            },
        ),
        migrations.CreateModel(
            name='MusicOnHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('mode', models.CharField(choices=[('files', 'Archivos'), ('quietmp3', 'MP3 Silencioso'), ('custom', 'Aplicación Personalizada')], default='files', max_length=20, verbose_name='Modo')),
                ('directory', models.CharField(blank=True, max_length=500, verbose_name='Directorio')),
                ('application', models.CharField(blank=True, max_length=500, verbose_name='Aplicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Música en Espera',
                'verbose_name_plural': 'Música en Espera',
                'db_table': 'music_on_hold',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('time_groups', models.JSONField(default=list, verbose_name='Grupos de horarios')),
                ('true_destination_type', models.CharField(choices=[('ivr', 'IVR'), ('queue', 'Cola'), ('extension', 'Extensión'), ('voicemail', 'Buzón de Voz'), ('announcement', 'Anuncio')], max_length=20, verbose_name='Tipo destino (true)')),
                ('true_destination', models.CharField(max_length=100, verbose_name='Destino (true)')),
                ('false_destination_type', models.CharField(choices=[('ivr', 'IVR'), ('queue', 'Cola'), ('extension', 'Extensión'), ('voicemail', 'Buzón de Voz'), ('announcement', 'Anuncio')], max_length=20, verbose_name='Tipo destino (false)')),
                ('false_destination', models.CharField(max_length=100, verbose_name='Destino (false)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condición de Horario',
                'verbose_name_plural': 'Condiciones de Horario',
                'db_table': 'time_conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voicemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox', models.CharField(max_length=20, unique=True, verbose_name='Buzón')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('email_attach', models.BooleanField(default=True, verbose_name='Adjuntar audio')),
                ('email_delete', models.BooleanField(default=False, verbose_name='Eliminar después de enviar')),
                ('max_messages', models.IntegerField(default=100, verbose_name='Mensajes máximos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buzón de Voz',
                'verbose_name_plural': 'Buzones de Voz',
                'db_table': 'voicemails',
                'ordering': ['mailbox'],
            },
        ),
        migrations.CreateModel(
            name='OutboundRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('pattern', models.CharField(max_length=50, verbose_name='Patrón')),
                ('prepend', models.CharField(blank=True, max_length=20, verbose_name='Prefijo agregar')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='Dígitos eliminar')),
                ('callerid_prefix', models.CharField(blank=True, max_length=50, verbose_name='Prefijo Caller ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_routes', to='telephony.siptrunk', verbose_name='Troncal')),
            ],
            options={
                'verbose_name': 'Ruta Saliente',
                'verbose_name_plural': 'Rutas Salientes',
                'db_table': 'outbound_routes',
                'ordering': ['name'],
            },
        ),
    ]
