# Generated by Django 4.2.9 on 2026-02-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0003_siptrunk_configuration_expansion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_start_t_e6c81a_idx',
            old_name='calls_start_t_e5e7db_idx',
        ),
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_agent_i_3202a5_idx',
            old_name='calls_agent_i_7b9f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_campaig_a1fb2d_idx',
            old_name='calls_campaig_a8c3e2_idx',
        ),
        migrations.AlterField(
            model_name='siptrunk',
            name='outbound_auth_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contraseña Saliente'),
        ),
        migrations.AlterField(
            model_name='siptrunk',
            name='outbound_auth_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuario Saliente'),
        ),
    ]
