# Generated by Django 4.2.9 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0004_rename_calls_start_t_e5e7db_idx_calls_start_t_e6c81a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundroute',
            name='priority',
            field=models.IntegerField(default=1, help_text='Orden de evaluación (menor = mayor prioridad)', verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='outboundroute',
            name='ring_time',
            field=models.IntegerField(default=60, help_text='Segundos a esperar antes de desistir', verbose_name='Tiempo de timbre (seg)'),
        ),
        migrations.AddField(
            model_name='outboundroute',
            name='dial_options',
            field=models.CharField(blank=True, default='trg', help_text='Opciones de Asterisk Dial: t=transfer, r=ring, g=continue, T=transfer caller, W=recording', max_length=50, verbose_name='Opciones Dial'),
        ),
        migrations.AlterModelOptions(
            name='outboundroute',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Ruta Saliente', 'verbose_name_plural': 'Rutas Salientes'},
        ),
    ]
