# Generated by Django 4.2.9

from django.db import migrations, models


def migrate_extension_types(apps, schema_editor):
    """
    Migrar extensiones existentes:
    - SIP → PJSIP (softphone tradicional)
    - IAX2 → PJSIP (no soportado, convertir a SIP)
    - PJSIP → se queda igual
    """
    Extension = apps.get_model('telephony', 'Extension')
    # Convertir SIP y IAX2 a PJSIP
    Extension.objects.filter(extension_type__in=['SIP', 'IAX2']).update(extension_type='PJSIP')


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0005_outboundroute_dial_options_outboundroute_priority_and_more'),
    ]

    operations = [
        # 1. Migrar datos existentes antes de cambiar choices
        migrations.RunPython(migrate_extension_types, migrations.RunPython.noop),

        # 2. Cambiar extension_type: nuevos choices y default
        migrations.AlterField(
            model_name='extension',
            name='extension_type',
            field=models.CharField(
                choices=[('PJSIP', 'SIP (Softphone)'), ('WEBRTC', 'WebRTC (Navegador)')],
                default='PJSIP',
                help_text='PJSIP para softphones (MicroSIP, Zoiper), WebRTC para navegador',
                max_length=10,
                verbose_name='Tipo',
            ),
        ),

        # 3. Agregar campo transport
        migrations.AddField(
            model_name='extension',
            name='transport',
            field=models.CharField(
                choices=[
                    ('transport-udp', 'UDP (Softphone)'),
                    ('transport-tcp', 'TCP'),
                    ('transport-wss', 'WSS (WebRTC)'),
                ],
                default='transport-udp',
                help_text='UDP para softphones, WSS para WebRTC',
                max_length=20,
                verbose_name='Transporte',
            ),
        ),

        # 4. Agregar campo max_contacts
        migrations.AddField(
            model_name='extension',
            name='max_contacts',
            field=models.IntegerField(default=1, verbose_name='Contactos máximos'),
        ),

        # 5. Agregar campo codecs
        migrations.AddField(
            model_name='extension',
            name='codecs',
            field=models.CharField(
                blank=True,
                default='ulaw,alaw,g722',
                help_text='Para WebRTC se agrega opus automáticamente',
                max_length=100,
                verbose_name='Códecs',
            ),
        ),
    ]
