# Generated by Django 4.2.9 on 2026-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0012_callback_webhook_dnc_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='extension',
            name='ext_type_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='inboundroute',
            name='inbound_active_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='outboundroute',
            name='outbound_active_priority_idx',
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='secret',
            field=models.CharField(max_length=100, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='siptrunk',
            name='inbound_auth_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contraseña Entrante'),
        ),
        migrations.AlterField(
            model_name='siptrunk',
            name='outbound_auth_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contraseña Saliente'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='payload',
            field=models.JSONField(verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='events',
            field=models.JSONField(default=list, help_text='Lista de slugs de eventos a notificar (vacío = todos).', verbose_name='Eventos'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret',
            field=models.CharField(blank=True, help_text='Si se establece, se firma el payload con HMAC-SHA256 en la cabecera X-Webhook-Signature.', max_length=200, verbose_name='Secret HMAC'),
        ),
    ]
