# Generated by Django 4.2.9 on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0013_remove_extension_ext_type_active_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivr',
            name='spoken',
            field=models.CharField(
                blank=True,
                help_text='Audio adicional (Playback) antes del menú. Ej: custom/ivr-spoken-principal',
                max_length=500,
                verbose_name='Spoken'
            ),
        ),
        migrations.AlterField(
            model_name='inboundroute',
            name='destination_type',
            field=models.CharField(
                choices=[
                    ('ivr', 'IVR'),
                    ('queue', 'Cola'),
                    ('extension', 'Extensión'),
                    ('voicemail', 'Buzón de Voz'),
                    ('announcement', 'Anuncio'),
                    ('custom_destination', 'Destino Personalizado'),
                ],
                max_length=20,
                verbose_name='Tipo destino'
            ),
        ),
    ]
