# Generated by Django 4.2.9 on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0014_ivr_spoken_and_inbound_custom_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivr',
            name='invalid_destination',
            field=models.CharField(blank=True, max_length=100, verbose_name='Destino inválido'),
        ),
        migrations.AddField(
            model_name='ivr',
            name='invalid_destination_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('queue', 'Cola'),
                    ('extension', 'Extensión'),
                    ('ivr', 'IVR'),
                    ('voicemail', 'Buzón de Voz'),
                    ('announcement', 'Anuncio'),
                    ('custom_destination', 'Destino Personalizado'),
                ],
                max_length=20,
                verbose_name='Tipo destino inválido',
            ),
        ),
        migrations.AddField(
            model_name='ivr',
            name='invalid_retries',
            field=models.IntegerField(default=3, verbose_name='Reintentos inválido'),
        ),
        migrations.AddField(
            model_name='ivr',
            name='timeout_destination',
            field=models.CharField(blank=True, max_length=100, verbose_name='Destino timeout'),
        ),
        migrations.AddField(
            model_name='ivr',
            name='timeout_destination_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('queue', 'Cola'),
                    ('extension', 'Extensión'),
                    ('ivr', 'IVR'),
                    ('voicemail', 'Buzón de Voz'),
                    ('announcement', 'Anuncio'),
                    ('custom_destination', 'Destino Personalizado'),
                ],
                max_length=20,
                verbose_name='Tipo destino timeout',
            ),
        ),
        migrations.AddField(
            model_name='ivr',
            name='timeout_retries',
            field=models.IntegerField(default=3, verbose_name='Reintentos timeout'),
        ),
    ]
