# Generated by Django 4.2.9 on 2026-02-01 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True, verbose_name='ID Agente')),
                ('sip_extension', models.CharField(max_length=20, unique=True, verbose_name='Extensión SIP')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Ocupado'), ('oncall', 'En Llamada'), ('break', 'En Descanso'), ('offline', 'Desconectado'), ('wrapup', 'Post-Llamada')], default='offline', max_length=20, verbose_name='Estado')),
                ('webrtc_enabled', models.BooleanField(default=True, verbose_name='WebRTC habilitado')),
                ('max_concurrent_calls', models.IntegerField(default=1, verbose_name='Llamadas concurrentes máx')),
                ('auto_answer', models.BooleanField(default=False, verbose_name='Auto-respuesta')),
                ('recording_enabled', models.BooleanField(default=True, verbose_name='Grabación habilitada')),
                ('current_calls', models.IntegerField(default=0, verbose_name='Llamadas actuales')),
                ('last_call_time', models.DateTimeField(blank=True, null=True, verbose_name='Última llamada')),
                ('logged_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Conectado desde')),
                ('last_status_change', models.DateTimeField(auto_now=True, verbose_name='Último cambio estado')),
                ('calls_today', models.IntegerField(default=0, verbose_name='Llamadas hoy')),
                ('talk_time_today', models.IntegerField(default=0, help_text='Segundos', verbose_name='Tiempo hablado hoy')),
                ('available_time_today', models.IntegerField(default=0, help_text='Segundos', verbose_name='Tiempo disponible hoy')),
                ('break_time_today', models.IntegerField(default=0, help_text='Segundos', verbose_name='Tiempo descanso hoy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('current_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_agents', to='campaigns.campaign')),
                ('campaigns', models.ManyToManyField(blank=True, related_name='agents', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='AgentBreakReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_paid', models.BooleanField(default=True, verbose_name='¿Es pagado?')),
                ('max_duration', models.IntegerField(blank=True, help_text='Minutos máximos', null=True, verbose_name='Duración máxima')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Razón de Descanso',
                'verbose_name_plural': 'Razones de Descanso',
                'db_table': 'agent_break_reasons',
            },
        ),
        migrations.CreateModel(
            name='AgentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Segundos')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='agents.agent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Historial Estado Agente',
                'verbose_name_plural': 'Historial Estados Agentes',
                'db_table': 'agent_status_history',
                'ordering': ['-started_at'],
            },
        ),
    ]
