# Generated by Django 4.2.9 on 2026-05-30 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_add_sip_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbreakreason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
