# Generated by Django 4.2.9 on 2026-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID del mensaje en la plataforma externa (WhatsApp, Twilio, etc.)', max_length=255, null=True),
        ),
    ]
