# Generated by Django 4.2.9 on 2026-02-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('extension', models.CharField(max_length=20, unique=True, verbose_name='Extensión')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('strategy', models.CharField(choices=[('ringall', 'Ring All - Timbran todos'), ('leastrecent', 'Least Recent - Menos reciente'), ('fewestcalls', 'Fewest Calls - Menos llamadas'), ('random', 'Random - Aleatorio'), ('rrmemory', 'Round Robin Memory'), ('linear', 'Linear - Lineal')], default='ringall', max_length=20, verbose_name='Estrategia')),
                ('timeout', models.IntegerField(default=30, verbose_name='Timeout (seg)')),
                ('retry', models.IntegerField(default=5, verbose_name='Reintentar después de (seg)')),
                ('max_wait_time', models.IntegerField(default=300, verbose_name='Tiempo máx. espera (seg)')),
                ('announce_frequency', models.IntegerField(default=30, verbose_name='Frecuencia anuncio (seg)')),
                ('announce_holdtime', models.BooleanField(default=True, verbose_name='Anunciar tiempo espera')),
                ('periodic_announce_frequency', models.IntegerField(default=60, verbose_name='Anuncio periódico (seg)')),
                ('music_on_hold', models.CharField(default='default', max_length=100, verbose_name='Música en espera')),
                ('max_callers', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Máx. llamadas')),
                ('service_level', models.IntegerField(default=60, help_text='Segundos', verbose_name='Nivel de servicio')),
                ('wrap_up_time', models.IntegerField(default=0, verbose_name='Tiempo post-llamada (seg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cola',
                'verbose_name_plural': 'Colas',
                'db_table': 'queues',
            },
        ),
        migrations.CreateModel(
            name='QueueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls_waiting', models.IntegerField(default=0, verbose_name='En espera')),
                ('calls_completed', models.IntegerField(default=0, verbose_name='Completadas')),
                ('calls_abandoned', models.IntegerField(default=0, verbose_name='Abandonadas')),
                ('avg_wait_time', models.IntegerField(default=0, help_text='Segundos', verbose_name='Tiempo espera promedio')),
                ('avg_talk_time', models.IntegerField(default=0, help_text='Segundos', verbose_name='Tiempo conversación promedio')),
                ('max_wait_time', models.IntegerField(default=0, help_text='Segundos', verbose_name='Tiempo espera máximo')),
                ('agents_available', models.IntegerField(default=0, verbose_name='Agentes disponibles')),
                ('agents_busy', models.IntegerField(default=0, verbose_name='Agentes ocupados')),
                ('service_level_met', models.IntegerField(default=0, verbose_name='Nivel servicio cumplido')),
                ('service_level_percentage', models.FloatField(default=0.0, verbose_name='% Nivel servicio')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='queues.queue')),
            ],
            options={
                'verbose_name': 'Estadísticas de Cola',
                'verbose_name_plural': 'Estadísticas de Colas',
                'db_table': 'queue_stats',
            },
        ),
    ]
