# Generated by Django 4.2.9 on 2026-02-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.IntegerField(default=0, verbose_name='Penalización')),
                ('paused', models.BooleanField(default=False, verbose_name='Pausado')),
                ('calls_taken', models.IntegerField(default=0, verbose_name='Llamadas atendidas')),
                ('last_call', models.DateTimeField(blank=True, null=True, verbose_name='Última llamada')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='queues.queue')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Miembro de Cola',
                'verbose_name_plural': 'Miembros de Colas',
                'db_table': 'queue_members',
                'unique_together': {('queue', 'agent')},
            },
        ),
    ]
