# Generated by Django 4.2.9 on 2026-02-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemember',
            name='agent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='queue_memberships',
                to='agents.agent',
                null=True,  # Permitir null temporalmente
            ),
        ),
        migrations.AlterUniqueTogether(
            name='queuemember',
            unique_together={('queue', 'agent')},
        ),
    ]
