# Generated by Django 4.2.9 on 2026-02-15 21:30

from django.db import migrations, models
import django.db.models.deletion


def remove_null_agents(apps, schema_editor):
    QueueMember = apps.get_model('queues', 'QueueMember')
    QueueMember.objects.filter(agent__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('queues', '0002_queuemember'),
    ]

    operations = [
        migrations.RunPython(
            code=remove_null_agents,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='queuemember',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='agents.agent'),
        ),
    ]
