# Generated by Django 4.2.9 on 2026-02-01 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('total_contacts', models.IntegerField(default=0, verbose_name='Total contactos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Contactos',
                'verbose_name_plural': 'Listas de Contactos',
                'db_table': 'contact_lists',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Teléfono 2')),
                ('phone3', models.CharField(blank=True, max_length=20, verbose_name='Teléfono 3')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='País')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('pending', 'Pendiente'), ('contacted', 'Contactado'), ('success', 'Exitoso'), ('failed', 'Fallido'), ('blacklisted', 'Lista Negra')], default='new', max_length=20, verbose_name='Estado')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridad')),
                ('attempts', models.IntegerField(default=0, verbose_name='Intentos')),
                ('last_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Último intento')),
                ('next_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Próximo intento')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Campos personalizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.contactlist')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contacts',
                'ordering': ['-priority', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Razón')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista Negra',
                'verbose_name_plural': 'Listas Negras',
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_important', models.BooleanField(default=False, verbose_name='Importante')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Contacto',
                'verbose_name_plural': 'Notas de Contactos',
                'db_table': 'contact_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_list', 'status'], name='contacts_contact_c87e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='contacts_phone_4a3b5c_idx'),
        ),
    ]
