# Generated by Django 4.2.9 on 2026-02-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='contacts_contact_2ce835_idx',
            old_name='contacts_contact_c87e9d_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='contacts_phone_3b79d2_idx',
            old_name='contacts_phone_4a3b5c_idx',
        ),
    ]
