# Generated by Django 4.2.9 on 2026-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_timezone_vip_dnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dnc_opt_out',
            field=models.BooleanField(default=False, help_text='Contacto solicitó no ser contactado.', verbose_name='No llamar (DNC)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='Ej: America/Bogota. El dialer no marcará fuera del horario local.', max_length=50, verbose_name='Zona horaria'),
        ),
    ]
