# Generated by Django 4.2.9 on 2026-02-15 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, verbose_name='Nombre archivo')),
                ('file_path', models.CharField(max_length=1000, verbose_name='Ruta archivo')),
                ('file_size', models.BigIntegerField(default=0, help_text='Bytes', verbose_name='Tamaño')),
                ('format', models.CharField(default='wav', max_length=10, verbose_name='Formato')),
                ('duration', models.IntegerField(default=0, help_text='Segundos', verbose_name='Duración')),
                ('codec', models.CharField(blank=True, max_length=50, verbose_name='Códec')),
                ('status', models.CharField(choices=[('recording', 'Grabando'), ('completed', 'Completada'), ('failed', 'Fallida'), ('archived', 'Archivada')], default='recording', max_length=20, verbose_name='Estado')),
                ('transcription', models.TextField(blank=True, verbose_name='Transcripción')),
                ('transcription_status', models.CharField(blank=True, max_length=20, verbose_name='Estado transcripción')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('access_count', models.IntegerField(default=0, verbose_name='Reproducciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording_detail', to='telephony.call')),
            ],
            options={
                'verbose_name': 'Grabación',
                'verbose_name_plural': 'Grabaciones',
                'db_table': 'recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Nota')),
                ('timestamp', models.IntegerField(default=0, help_text='Segundo de la grabación', verbose_name='Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='recordings.recording')),
            ],
            options={
                'verbose_name': 'Nota de Grabación',
                'verbose_name_plural': 'Notas de Grabaciones',
                'db_table': 'recording_notes',
                'ordering': ['timestamp', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.IntegerField(default=0, verbose_name='Saludo')),
                ('clarity', models.IntegerField(default=0, verbose_name='Claridad')),
                ('professionalism', models.IntegerField(default=0, verbose_name='Profesionalismo')),
                ('resolution', models.IntegerField(default=0, verbose_name='Resolución')),
                ('closing', models.IntegerField(default=0, verbose_name='Cierre')),
                ('total_score', models.IntegerField(default=0, verbose_name='Puntuación total')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('feedback_sent', models.BooleanField(default=False, verbose_name='Feedback enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='recordings.recording')),
            ],
            options={
                'verbose_name': 'Evaluación de Grabación',
                'verbose_name_plural': 'Evaluaciones de Grabaciones',
                'db_table': 'recording_evaluations',
            },
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['created_at'], name='recordings_created_a_3b26c7_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['agent', 'created_at'], name='recordings_agent_c_b915c6_idx'),
        ),
        migrations.AddIndex(
            model_name='recording',
            index=models.Index(fields=['campaign', 'created_at'], name='recordings_campaig_f9a8ed_idx'),
        ),
    ]
