# Generated by Django 4.2.9 on 2026-02-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recording',
            new_name='recordings_created_3645f5_idx',
            old_name='recordings_created_a_3b26c7_idx',
        ),
        migrations.RenameIndex(
            model_name='recording',
            new_name='recordings_agent_i_937b61_idx',
            old_name='recordings_agent_c_b915c6_idx',
        ),
        migrations.RenameIndex(
            model_name='recording',
            new_name='recordings_campaig_b11e57_idx',
            old_name='recordings_campaig_f9a8ed_idx',
        ),
    ]
