# Generated by Django 4.2.9 on 2026-02-15 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('report_type', models.CharField(choices=[('campaign', 'Campaña'), ('agent', 'Agente'), ('queue', 'Cola'), ('calls', 'Llamadas'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10, verbose_name='Formato')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros')),
                ('date_from', models.DateTimeField(verbose_name='Desde')),
                ('date_to', models.DateTimeField(verbose_name='Hasta')),
                ('file_path', models.CharField(blank=True, max_length=1000, verbose_name='Archivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamaño')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje error')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Programado')),
                ('schedule_frequency', models.CharField(blank=True, max_length=20, verbose_name='Frecuencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
